### ISSUE TITLE
Program doesn't work

### ISSUE THREAD

**Issue by Zerogoki00** [SneakyAzWhat/RDR2PhotoConverter#3]
I installed NET runtime but nothing happens when I try to run this program. I start exe and nothing happens, process just dies 

Windows 10 x64 21H2

**Comment by SneakyAzWhat** [comment]
Do you have an antivirus? Your description matches what happened to other users who had an AV blocking the program. If so I would either allow the program or disable the AV temporarily to see if that fixes the problem for ya.

**Comment by Zerogoki00** [comment]
@SneakyAzWhat I don't have any antivirus other than microsoft defender

**Comment by SneakyAzWhat** [comment]
Can you try the first release of the program (v1.0) and let me know if that version works?

**Comment by Zerogoki00** [comment]
@SneakyAzWhat I just tried and the same thing happens :(
Is there any way to get log or debug this somehow?

**Comment by SneakyAzWhat** [comment]
> @SneakyAzWhat I just tried and the same thing happens :(
> Is there any way to get log or debug this somehow?

Hmm this is really strange behavior because 1.0 worked for everyone outside of something interfering with it. So if both versions aren't working then I'm thinking something on your pc is blocking it. 

I'll try to create a version for you with more logging to see if we can catch what's killing the application.

**Comment by SneakyAzWhat** [comment]
Did you go into windows defender and manually allow the program?

Try reinstalling the .net runtime as well https://dotnet.microsoft.com/en-us/download/dotnet/5.0

I had a few people test on both windows 10 and 11 and no issues reported. After you've tried these 2 things I will look at trying to find a way to catch whats killing the application if it is closing on launch.

**Comment by Zerogoki00** [comment]
@SneakyAzWhat 
I just found crash dumps of this program in `AppData\Local\CrashDumps`

I uploaded it [here](https://disk.yandex.ru/d/jef8HQaat_yHjw)
Maybe it can help you

**Comment by SneakyAzWhat** [comment]
So you're getting an exception that relates to a few things. It could be a driver issue or just a bad install of .net https://thegeekpage.com/how-to-solve-unknown-software-exception-0xe0434352/

try reinstalling .net from this link, its the latest version. I want to see if maybe your .net install is the problem. you and one other person are reporting this problem. https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-5.0.17-windows-x64-installer

ALSO, this could be related to permissions on your system POSSIBLY.  Here are some additional troubleshooting steps, Please run the application between troubleshooting so we can try to narrow down a solution if we find one. https://appuals.com/how-to-fix-application-error-0xe0434352-on-windows/

**Comment by SneakyAzWhat** [comment]
@Zerogoki00 Did you try the above things? Also one other thing, have you tried running the program as administrator?

**Comment by SneakyAzWhat** [comment]
Anyone experiencing this problem can try downloading the latest release. If you get a pop-up when launching the application then please provide a screenshot. Thanks https://github.com/SneakyAzWhat/RDR2PhotoConverter/releases/tag/v1.3

**Comment by SifatIbna** [comment]
Its still not working for me. I've currently dotnet in my pc but its still poping the installation window. after clicking yes, its not going anywhere
<img width="691" alt="image" src="https://github.com/SneakyAzWhat/RDR2PhotoConverter/assets/50807611/1e8d30e1-df39-4e34-a6b5-525740c69a61">

**Comment by SneakyAzWhat** [comment]
> Its still not working for me. I've currently dotnet in my pc but its still poping the installation window. after clicking yes, its not going anywhere <img alt="image" width="691" src="https://private-user-images.githubusercontent.com/50807611/273407821-1e8d30e1-df39-4e34-a6b5-525740c69a61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNDUzMzUsIm5iZiI6MTcxNDM0NTAzNSwicGF0aCI6Ii81MDgwNzYxMS8yNzM0MDc4MjEtMWU4ZDMwZTEtZGYzOS00ZTM0LWE2YjUtNTI1NzQwYzY5YTYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDIyNTcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MmI4MTA3MDQwMGQwZjEwNjkzYjZlMTcwMTE4M2I5MmFjMzgwODk0ZTI0YTg3MzQ1NzdhN2MwM2EwZjY5OWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ubtD_6cI_dP9b8D2dykDbCXHD-gmd0M56yaekh-HqmY">

You're missing [.net 5 runtime](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-5.0.17-windows-x64-installer) 

also there is a new version so you can try downloading the runtime and [new app version](https://github.com/SneakyAzWhat/RDR2PhotoConverter/releases/tag/v1.4) and see if you continue having problems. I haven't looked at the code on this in a while so if you're still experiencing problems after downloading .net 5 runtime and the v1.4 app version I'll dive into this and see what might need to be changed.
