### ISSUE TITLE
Constantly being prompted to install .NET even after installing it

### ISSUE THREAD

**Issue by TheOriginalBob0705** [SneakyAzWhat/RDR2PhotoConverter#4]
Program keeps asking to install .NET even after it has been installed

Additionally, when pressing the button to install .NET, nothing happens. I had to manually go to the link in the README to download it and even then it still shows the same popup to "install .NET"

**Comment by SneakyAzWhat** [comment]
1) Can you include a screenshot of these pop ups asking you to install .net?
2) Can you open your command prompt and type: `dotnet --list-runtimes` and screenshot the results?

Thanks

**Comment by advanced-bencoding** [comment]
> Program keeps asking to install .NET even after it has been installed
> 
> Additionally, when pressing the button to install .NET, nothing happens. I had to manually go to the link in the README to download it and even then it still shows the same popup to "install .NET"

Hi, can you try with .NET 5.0.14?

**Comment by SneakyAzWhat** [comment]
Closing this for now due to no response from the OP. Please create another issue if you continue to experience a problem and are ready to troubleshoot to help narrow down the cause. Thanks

**Comment by CptPakundo** [comment]
> > Program keeps asking to install .NET even after it has been installed
> > Additionally, when pressing the button to install .NET, nothing happens. I had to manually go to the link in the README to download it and even then it still shows the same popup to "install .NET"
> 
> Hi, can you try with .NET 5.0.14?

Hi, not OP, but...
Installing that solved the problem for me.
